### ISSUE TITLE
Shield TV - Only 10 Items Per Row

### ISSUE THREAD

**Issue by sysmoon14** [sarendsen/replex#29]
For collections shown via replex, my Shield TV only shows 10 items per row. Without replex, I can continue scrolling for the entirety of the collection.

**Comment by sysmoon14** [comment]
Yeah that's not the case here, I disabled that functionality

**Comment by jl94x4** [comment]
Not sure what you changed, but I updated just now and the recently added rows I spoke about above are working again.

**Comment by jl94x4** [comment]
I updated today, It now appears on the home screen but clicking on the row shows this error.

![image](https://github.com/sarendsen/replex/assets/18123855/fd71b2e5-6c15-4903-ab9a-f99ca0bb0f37)

**Comment by jl94x4** [comment]
I've opened a new issue #35

**Comment by sysmoon14** [comment]
Tested on the latest version (0.9.11) and still seeing issues. I have a bit more info though...

This seems to work on non-hero rows, but for hero rows (labeled REPLEXHERO) it still only displays 10 items per library. So for a hero row consisting of 2 libraries there are 20 items, but hero rows for a single library only show 10.

**Comment by sysmoon14** [comment]
Plex version 9.29.0.3347

Note. I'm seeing the same behaviour on android mobile, the only difference is the mobile gives me a "View all" button after the 10th/20th item

**Comment by sysmoon14** [comment]
Were you able to reproduce this? I can give you access to my server if it helps.

**Comment by sysmoon14** [comment]
It's not working for me on my Shield Android TV Plex App.

On my home I have 3 different types of rows:

1. Posters with content from 2 libraries (TV and Movies) - e.g. "Top This Week"
2. Heroes with content from 2 libraries (TV and Movies) - e.g. "Certified Fresh New Content"
3. Heroes with content from 1 library (TV only) - e.g. "Binge-Able Sit-Coms"

I'm seeing 3 different types of behaviour on my plex home screen.

For row type 1, it shows 10 items per library (alternating between Movies and TV) - then after 20 items it repeats the same 20 again, but continues on to show the full collection contents.

For row type 2, it shows 10 items per library (alternating between Movies and TV) - then after 20 items it stops, even though the collections contain more.

For row type 3, it shows 10 items and then stops scrolling - even though the collection contains more.

If I disable Replex, all of these rows continue to scroll until I see everything in the collection.

**Comment by sysmoon14** [comment]
0.10.7 resolved the issues with row type 1 above. I'm still only seeing a max of 10 items per library when I merge rows and display them as heroes - so row type 2 and 3 are still not working.

**Comment by sysmoon14** [comment]
Nope, I'm only looking on home. I took a short video - [link here](https://drive.google.com/file/d/1k2XbWBJ-NLwbZsXM1tboOkqu6xM8uBsI/view?usp=sharing). The video shows the issue with row type 1, which you can ignore, so skip to about 56 seconds.

I'll try it on my Philips Android TV to see if it's just a chrome issue. Did you try it with my server that I shared with you?

**Comment by sysmoon14** [comment]
Yep same issue on my Philips Android TV. Ok thanks

**Comment by sysmoon14** [comment]
Yep that's much better now, thank you! I'll close this issue.
