### ISSUE TITLE
Replex error 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Rustyt23** [sarendsen/replex#7]
i am using plex on port 32400 and for plex I used nginx on port 80 for reverse proxy but when i launched replex using docker with command "docker run -d -e RUST_LOG="debug"  -p 3001:80 -e REPLEX_HOST="http://localhost:32400" ghcr.io/sarendsen/replex "
i was getting error (port already in use) so i stopped nginx and destroyed old replex container , and again i used "docker run -d -e RUST_LOG="debug"  -p 3001:80 -e REPLEX_HOST="http://localhost:32400" ghcr.io/sarendsen/replex " but i am getting this error paste below. Can you help me with this please

2023-08-02T15:25:52.888063Z  INFO salvo_core::server: listening [HTTP/1.1] on http://0.0.0.0:80
2023-08-02T15:26:14.723056Z DEBUG hyper::proto::h1::io: parsed 3 headers
2023-08-02T15:26:14.723888Z DEBUG hyper::proto::h1::conn: incoming body is empty
2023-08-02T15:26:14.727843Z DEBUG Request{remote_addr=socket://172.17.0.1:56280 version=HTTP/1.1 method=GET path=http://localhost:3001/}: reqwest::connect: starting new connection: http://localhost:32400/    
2023-08-02T15:26:14.730035Z DEBUG hyper::client::connect::dns: resolving host="localhost"
2023-08-02T15:26:14.733822Z DEBUG Request{remote_addr=socket://172.17.0.1:56280 version=HTTP/1.1 method=GET path=http://localhost:3001/}: hyper::client::connect::http: connecting to 127.0.0.1:32400
2023-08-02T15:26:14.734121Z DEBUG Request{remote_addr=socket://172.17.0.1:56280 version=HTTP/1.1 method=GET path=http://localhost:3001/}: hyper::client::connect::http: connecting to [::1]:32400
2023-08-02T15:26:14.734639Z ERROR Request{remote_addr=socket://172.17.0.1:56280 version=HTTP/1.1 method=GET path=http://localhost:3001/}: salvo_proxy: get response data failed error=Other(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(32400), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" })) }) uri=http://localhost:3001/
2023-08-02T15:26:14.734805Z DEBUG Request{remote_addr=socket://172.17.0.1:56280 version=HTTP/1.1 method=GET path=http://localhost:3001/}: replex::logging: Response status=500 Internal Server Error duration=7.819541ms
SpanData { span_context: SpanContext { trace_id: 2f1632b676bad355afc13588ec56724f, span_id: 5bf0379c689d11dc, trace_flags: TraceFlags(1), is_remote: false, trace_state: TraceState(None) }, parent_span_id: 0000000000000000, span_kind: Internal, name: "Request", start_time: SystemTime { tv_sec: 1690989974, tv_nsec: 725147094 }, end_time: SystemTime { tv_sec: 1690989974, tv_nsec: 734972094 }, attributes: EvictedHashMap { map: {Static("remote_addr"): String(Owned("socket://172.17.0.1:56280")), Static("code.lineno"): I64(23), Static("thread.name"): String(Owned("tokio-runtime-worker")), Static("thread.id"): I64(2), Static("version"): String(Owned("HTTP/1.1")), Static("path"): String(Owned("http://localhost:3001/")), Static("method"): String(Owned("GET")), Static("code.filepath"): String(Static("src/logging.rs")), Static("busy_ns"): I64(4007083), Static("idle_ns"): I64(5838208), Static("code.namespace"): String(Static("replex::logging"))}, evict_list: [Static("idle_ns"), Static("busy_ns"), Static("path"), Static("method"), Static("version"), Static("remote_addr"), Static("thread.name"), Static("thread.id"), Static("code.lineno"), Static("code.namespace"), Static("code.filepath")], max_len: 128, dropped_count: 0 }, events: EvictedQueue { queue: Some([Event { name: "starting new connection: http://localhost:32400/", timestamp: SystemTime { tv_sec: 1690989974, tv_nsec: 727824219 }, attributes: [KeyValue { key: Static("level"), value: String(Static("DEBUG")) }, KeyValue { key: Static("target"), value: String(Owned("reqwest::connect")) }, KeyValue { key: Static("code.filepath"), value: String(Owned("/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.18/src/connect.rs")) }, KeyValue { key: Static("code.namespace"), value: String(Owned("reqwest::connect")) }, KeyValue { key: Static("code.lineno"), value: I64(429) }], dropped_attributes_count: 0 }, Event { name: "connecting to 127.0.0.1:32400", timestamp: SystemTime { tv_sec: 1690989974, tv_nsec: 733798553 }, attributes: [KeyValue { key: Static("level"), value: String(Static("DEBUG")) }, KeyValue { key: Static("target"), value: String(Static("hyper::client::connect::http")) }, KeyValue { key: Static("code.filepath"), value: String(Static("/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/client/connect/http.rs")) }, KeyValue { key: Static("code.namespace"), value: String(Static("hyper::client::connect::http")) }, KeyValue { key: Static("code.lineno"), value: I64(537) }], dropped_attributes_count: 0 }, Event { name: "connecting to [::1]:32400", timestamp: SystemTime { tv_sec: 1690989974, tv_nsec: 734118844 }, attributes: [KeyValue { key: Static("level"), value: String(Static("DEBUG")) }, KeyValue { key: Static("target"), value: String(Static("hyper::client::connect::http")) }, KeyValue { key: Static("code.filepath"), value: String(Static("/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/client/connect/http.rs")) }, KeyValue { key: Static("code.namespace"), value: String(Static("hyper::client::connect::http")) }, KeyValue { key: Static("code.lineno"), value: I64(537) }], dropped_attributes_count: 0 }, Event { name: "get response data failed", timestamp: SystemTime { tv_sec: 1690989974, tv_nsec: 734466428 }, attributes: [KeyValue { key: Static("level"), value: String(Static("ERROR")) }, KeyValue { key: Static("target"), value: String(Static("salvo_proxy")) }, KeyValue { key: Static("error"), value: String(Owned("Other(reqwest::Error { kind: Request, url: Url { scheme: \"http\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"localhost\")), port: Some(32400), path: \"/\", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError(\"tcp connect error\", Os { code: 99, kind: AddrNotAvailable, message: \"Cannot assign requested address\" })) })")) }, KeyValue { key: Static("uri"), value: String(Owned("http://localhost:3001/")) }, KeyValue { key: Static("code.filepath"), value: String(Static("/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/salvo-proxy-0.49.1/src/lib.rs")) }, KeyValue { key: Static("code.namespace"), value: String(Static("salvo_proxy")) }, KeyValue { key: Static("code.lineno"), value: I64(259) }], dropped_attributes_count: 0 }, Event { name: "Response", timestamp: SystemTime { tv_sec: 1690989974, tv_nsec: 734799511 }, attributes: [KeyValue { key: Static("level"), value: String(Static("DEBUG")) }, KeyValue { key: Static("target"), value: String(Static("replex::logging")) }, KeyValue { key: Static("status"), value: String(Owned("500 Internal Server Error")) }, KeyValue { key: Static("duration"), value: String(Owned("7.819541ms")) }, KeyValue { key: Static("code.filepath"), value: String(Static("src/logging.rs")) }, KeyValue { key: Static("code.namespace"), value: String(Static("replex::logging")) }, KeyValue { key: Static("code.lineno"), value: I64(38) }], dropped_attributes_count: 0 }]), max_len: 128, dropped_count: 0 }, links: EvictedQueue { queue: None, max_len: 128, dropped_count: 0 }, status: Error { description: "" }, resource: Resource { attrs: {Static("service.name"): String(Owned("unknown_service"))}, schema_url: None }, instrumentation_lib: InstrumentationLibrary { name: "opentelemetry", version: Some("0.19.0"), schema_url: None } }
2023-08-02T15:26:14.737150Z DEBUG hyper::proto::h1::io: flushed 1284 bytes
2023-08-02T15:26:14.737868Z DEBUG hyper::proto::h1::conn: read eof

**Comment by Rustyt23** [comment]
no good my updated command was docker run -d -e RUST_LOG="debug"  -p 3001:80 -e REPLEX_HOST="http://0.0.0.0:32400" ghcr.io/sarendsen/replex, m getting same error on replex docker log when i visit localhost:3001 on browser

**Comment by Rustyt23** [comment]
i have tried 127.0.0.1:32400 also and i'm not running plex on docker its running on the system (binary)

**Comment by darthShadow** [comment]
Try adding `--network="host"` to the docker run command.

Reference: https://docs.docker.com/engine/reference/run/#network-host

**Comment by Rustyt23** [comment]
@darthShadow --network="host" did not help instead i used replex binary and this is  doing fine for me  
P.S i'm using replex on Mac OS

**Comment by darthShadow** [comment]
Ah, yeah, the host network is on the docker VM and not the MAC itself so it won't be able to connect to Plex.
